save_dir = "Monodomain_2d"
mesh_path = "/home/mathias/Chaste/mesh/test/data/2D_0_to_1mm_200_elements"
stimulus_type = "simple"

# Time paramters in millisec
sim_duration = 6000.0
ode_timestep = 0.1
pde_timestep = 0.1
print_timestep = 1.0

# Cell parameters
cell_type = "Means"

[HodgkinHuxley]
	# Stimulus parameters
	x_stim_start = 0.049
	x_stim_end = 0.051
	y_stim_start = 0.049
	y_stim_end = 0.051

	# Cell properties
	capacitance = 1.0 # uF/cm2
	conductivities = [0.06, 0.03] #x, y

	# Stimulus
	magnitude = -2e5 # uA/cm2
	period = 10.0 #ms
	duration = 0.5 # ms
	start_time = 300.0 # ms

	cell_id = 0

[ChayKeizer]
	# Stimulus parameters
	x_stim_start = 0.0
	x_stim_end = 0.0
	y_stim_start = 0.0
	y_stim_end = 0.0

	# Cell properties
	capacitance = 5300.0 # uF/cm2
	conductivities = [0.0, 0.0] #x, y

	# Stimulus
	magnitude = 0.0 # uA/cm2
	period = 0.1 # ms
	duration = 0.5 # ms
	start_time = 5.0 # ms

	cell_id = 1

[Means]
	# Stimulus parameters
	x_stim_start = 0.04
	x_stim_end = 0.06
	y_stim_start = 0.04
	y_stim_end = 0.06

	# Cell properties
	capacitance = 1.0 # uF/cm2
	conductivities = [0.3, 0.3] #x, y

	# Stimulus
	magnitude = -0.5e5 # uA/cm2
	period = 0.1 # ms
	duration = 2000.0 # ms
	start_time = 1000.0 # ms

	cell_id = 2
