save_dir = "Monodomain_2d"
mesh_name = "2D_0_1mm_200_elements"
mesh_dir = "/home/mathias/Chaste/mesh/test/data/"
stimulus_type = "regular"

# Time paramters in millisec
sim_duration = 600.0
ode_timestep = 0.01
pde_timestep = 0.01
print_timestep = 1.0

# Cell parameters
cell_type = "HodgkinHuxley"

[HodgkinHuxley]
	# Stimulus parameters
	x_stim_start = 0.04
	x_stim_end = 0.06
	y_stim_start = 0.0
	y_stim_end = 0.0

	# Cell properties
	capacitance = 1.0 # uF/cm2
	conductivities = [0.05, 0.05] #x, y

	# Stimulus
	magnitude = -2e5 # uA/cm2
	period = 50.0 #ms
	duration = 0.5 # ms
	start_time = 5.0 # ms

	cell_id = 0

[ChayKeizer]
	# Stimulus parameters
	x_stim_start = 0.0
	x_stim_end = 0.0
	y_stim_start = 0.0
	y_stim_end = 0.0

	# Cell properties
	capacitance = 5300.0 # uF/cm2
	conductivities = [0.0, 0.05] #x, y

	# Stimulus
	magnitude = 0.0 # uA/cm2
	period = 0.1 # ms
	duration = 0.5 # ms
	start_time = 5.0 # ms

	cell_id = 1

[Means]
	# Stimulus parameters
	x_stim_start = 0.00
	x_stim_end = 0.06
	y_stim_start = 0.00
	y_stim_end = 0.06

	# Cell properties
	capacitance = 1.0 # uF/cm2
	conductivities = [0.0, 0.0] #x, y

	# Stimulus
	magnitude = -0.5e3 # uA/cm2
	period = 0.1 # ms
	duration = 2000.0 # ms
	start_time = 1000.0 # ms

	cell_id = 2

[Tong]
	# Stimulus parameters
	x_stim_start = 0.00
	x_stim_end = 0.06
	y_stim_start = 0.00
	y_stim_end = 0.06

	# Cell properties
	capacitance = 1.0 # uF/cm2
	conductivities = [0.0, 0.0] #x, y

	# Stimulus
	magnitude = -0.25e3 # uA/cm2
	period = 0.1 # ms
	duration = 2000.0 # ms
	start_time = 1000.0 # ms

	cell_id = 3
