sim_duration = 1000.0 #ms
mesh_path = "/home/mathias/Chaste/mesh/test/data/2D_0_to_1mm_200_elements"
conductivities = [0.0, 0.0] #x, y
capacitance = 5300.0 # uF/cm2
cell_type = "ChayKeizer"
ode_timestep = 1.0 # ms
pde_timestep = 1.0 # ms
print_timestep = 1.0 # ms

[HodgkinHuxley]
	x_stim_start = 0.0
	x_stim_end = 0.04
	y_stim_start = 0.0
	y_stim_end = 0.02
	cell_id = 0

[ChayKeizer]
	x_stim_start = 0.0
	x_stim_end = 0.0
	y_stim_start = 0.0
	y_stim_end = 0.0
	cell_id = 1
