# General parameters
save_dir = "Monodomain_3d"
mesh_name = "rat_uterus_idealised_10mm_4704_elem"
mesh_dir = "/mesh/custom/"
stimulus_type = "simple"

# Stimulus parameters
x_stim_start = 0.00
x_stim_end = 0.06
y_stim_start = 0.00
y_stim_end = 0.06
z_stim_start = 0.0
z_stim_end = 0.04

# Time paramters in millisec
sim_duration = 10000.0
ode_timestep = 0.01
pde_timestep = 0.01
print_timestep = 1.0

# Cell parameters
cell_type = "Means"
