save_dir = "Monodomain_3d"
mesh_name = "3D_0_to_1mm_6000_elements"
mesh_dir = "/home/mathias/Chaste/mesh/test/data/"
stimulus_type = "simple"

# Time paramters in millisec
sim_duration = 7000.0
ode_timestep = 0.01
pde_timestep = 0.01
print_timestep = 1.0

# Cell parameters
cell_type = "HodgkinHuxley"
