# Stimulus parameters
x_stim_start = 0.0
x_stim_end = 0.0
y_stim_start = 0.0
y_stim_end = 0.0
z_stim_start = 0.0
z_stim_end = 0.04

# Cell properties
capacitance = 5300.0 # uF/cm2
conductivities = [0.0, 0.05, 0.01] #x, y, z

# Stimulus
magnitude = 0.0 # uA/cm2
period = 0.1 # ms
duration = 0.5 # ms
start_time = 5.0 # ms

cell_id = 1
