# Cell properties
capacitance = 1.0 # uF/cm2
conductivities_2d = [2500.0, 2500.0] #x, y
conductivities_3d = [2500.0, 2500.0, 2500.0] #x, y, z

# Stimulus
magnitude = -2e5 # uA/cm2
period = 20.0 #ms
duration = 10.0 # ms
start_time = 5.0 # ms

cell_id = 0
