# Cell properties
capacitance = 1.0 # uF/cm2
conductivities_2d = [0.13, 0.13] #x, y
conductivities_3d = [300.0, 300.0, 300.0] #x, y, z

# Stimulus
magnitude = -1.3e3 # uA/cm2
period = 60.0 # ms
duration = 40.0 # ms
start_time = 1000.0 # ms

cell_id = 2

# Cell parameters
[parameters]
   gna = 0.0895 # 0.0895 range 0.028 - 0.125
   beta = 0.015 # 0.015
   gk1 = 0.52 # 0.7 range 0.52 - 0.85
   gcal = 0.8 # 0.6
   gcat = 0.058 # 0.058
