# Cell properties
capacitance = 1.0 # uF/cm2
conductivities = [0.0, 0.0, 0.0] #x, y, z

# Stimulus
magnitude = -0.5e3 # uA/cm2
period = 0.1 # ms
duration = 2000.0 # ms
start_time = 1000.0 # ms

cell_id = 2

# Cell parameters
[parameters]
   gna = 0.1
   beta = 0.015
   gk1 = 0.75
