# Cell properties
capacitance = 1.0 # uF/cm2
conductivities = [0.013, 0.013, 0.013] #x, y, z

# Stimulus
magnitude = -1.3e3 # uA/cm2
period = 0.1 # ms
duration = 5000.0 # ms
start_time = 1000.0 # ms

cell_id = 2

# Cell parameters
[parameters]
   gna = 0.0895 # 0.0895 range 0.028 - 0.125
   beta = 0.015 # 0.015
   gk1 = 0.52 # 0.7 range 0.52 - 0.85
   gcal = 0.8 # 0.6
   gcat = 0.058 # 0.058
