# Stimulus parameters
x_stim_start = 0.00
x_stim_end = 0.06
y_stim_start = 0.00
y_stim_end = 0.06
z_stim_start = 0.0
z_stim_end = 0.04

# Cell properties
capacitance = 1.0 # uF/cm2
conductivities = [0.0, 0.0] #x, y, z

# Stimulus
magnitude = -0.25e3 # uA/cm2
period = 0.1 # ms
duration = 2000.0 # ms
start_time = 1000.0 # ms

cell_id = 3

# Cell parameters
[parameters]
   gna = 0.1
   gherg = 0.1
   gkq1 = 0.03
   gkq4 = 0.02
   gkq5 = 0.02
   beta = 0.015
   gk1 = 0.75
