# Cell properties
capacitance = 1.0 # uF/cm2
conductivities = [0.0, 0.0, 0.0] # x, y, z

# Stimulus
magnitude = -2.50e2 # uA/cm2
period = 0.1 # ms
duration = 5000.0 # ms
start_time = 1000.0 # ms

cell_id = 3

# Cell parameters
[parameters]
   gna = 0.0 # 0.0 range 0.028 - 0.125
   gkq1 = 0.0032 # 0.0032 range 0 - 0.0472
   gkq4 = 0.024 # 0.024 range 0 - 0.0208
   gkq5 = 0.016 # 0.016 range 0 - 0.036
   gherg = 0.08 # 0.08 range 0 - 0.176
   beta = 0.015 # 0.015
   gk1 = 0.24 # 0.24
